### ISSUE TITLE
とりあえずSubmit

### ISSUE THREAD

**Issue by mohira** [mohira/titanic_mobpro_0819#1]
## 概要
- とりあえずSubmitする(方法はなんでもおk)

## やること
- [x] ~~手法どうするか決める~~ -> ランダムフォレスト
- [x] 実装
    - [x] csv読み込む
    - [x] ダミー変数変換
        - [x] まずは性別をダミーに変換する
        - [x] ダミー変数化する関数を作る
    - [x] 欠損値補完
        - [x] Ageの欠損値補完する
    - [x] sklearnランダムフォレストでテストデータの予測スコアを計算する
        - [x] データ分割とか一切しない！
    - [x] kaggleでsubmitする
        - [x] CSVファイルに出力する
        - [x] 提出する

**Comment by keng000** [comment]
jupyter notebook にショートカットを追加する。
https://teratail.com/questions/73836

**Comment by sarrrrry** [comment]
終わった税
