### ISSUE TITLE
精度を上げる

### ISSUE THREAD

**Issue by sarrrrry** [mohira/titanic_mobpro_0819#7]
- [x] 目標を決める
    - [ ] spreadsheet で特徴量エンジニアリングシートを作る
        - [ ] 思いつく手法を羅列する

**Comment by mohira** [comment]
写メ参照でよろ

**Comment by sarrrrry** [comment]
![20180825_195153](https://user-images.githubusercontent.com/24644575/44617629-fa289f00-a8a0-11e8-9422-a38108b74379.jpg)

**Comment by sarrrrry** [comment]
学び：スプレッドシートとかにテンプレート決めて書き続けるより、一旦ホワイトボードに羅列してみるほうが良かった

**Comment by mohira** [comment]
学び: 付箋あるよ良さげ
